name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        osDist:
          - ubuntu
          - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/${{matrix.osDist}}.Dockerfile
          push: false
          tags: local/temp:latest-${{matrix.osDist}}

